build:
  environment:
          php: '5.6.0'

  tests:
    override:
      -
        command: 'vendor/bin/phpspec run -c ci/phpspec-with-coverage.yml'
        coverage:
          file: 'coverage.clover'
          format: 'php-clover'

tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
    sensiolabs_security_checker: true
    php_mess_detector:
        config:
            ruleset: ci/phpmd.xml

checks:
    php:
        code_rating: true
        duplication: true

build_failure_conditions:
    - 'elements.rating(<= B).exists'                # No classes/methods with a rating of B or worse
    - 'issues.label("coding-style").exists'         # No coding style issues allowed
    - 'issues.severity(>= INFO).exists'             # New issues of major or higher severity
    - 'project.metric("scrutinizer.quality", < 10)' # Code Quality Rating drops below 10
    - 'project.metric("scrutinizer.test_coverage", < 1)' # Code Coverage drops below 100%
